### ISSUE TITLE
Database design

### ISSUE THREAD

**Issue by ghost** [karyall/Plorist-Future#1]
Design of the whole Database
- [x] Research of data modeling & database normalization
- [x] Prepare basic list of objects and their classes
- [x] Collect RAW data for most entities of the app
- [ ] Analysis and research of entities
- [ ] Prepare basic list of entities
- [ ] Standardization & normalization of entities
- [ ] Design ERD
- [ ] Flow Chart or Data Flow Diagram
- [ ] Draw UML diagrams

**Notes:**
- Start the top-down data modeling because the data is in raw form
- Data modeling must be done consistently across system to achieve data compatibility
- Usage of the same data structures for storing and accessing data will give us the ability of sharing the data between different apps
- Exactly identify Entities types to avoid replication
- The structure and meaning of data must be standardized to be electronically shared with customers and suppliers

**Comment by mbrig-co** [comment]
The following list of entities prepared as a starting point of modeling:

1. Dahsboard
2. Billing
    2.1. Purchases Bills
    2.2. Sales Bills
3. Ledger
    3.1. Customers
    3.2. Vendors (Suppliers)
    3.3. Accounts
4. Expenses
5. Journal
6. Items
    6.1. Purchased Items (Bought Items)
    6.2. Sold Items
    6.3. Items List
    6.4. Companies & Types
    6.5. Warehouses
7. Users

**Comment by mbrig-co** [comment]
Change the Ledger section to become without sub-sections mean only one major section ledger or accounts is enough so instead of having sub-sections for each type of accounts create accounts with different types like: Customer Account, Vendor/Supplier Account and General or Personal Account.

**Comment by mbrig-co** [comment]
Basic objects list

| \# | Object Name | Class |
| ----- | ----- | ----- |
| 1 | User | Employee |
| 2 | Customer Individual | Person or Human |
| 3 | Customer Organization | Company or Organization |
| 4 | Vendor or Supplier Individual | Person or Human |
| 5 | Vendor or Supplier Organization | Company or Organization |
| 6 | Item or Product | Item or Product |
| 7 | Item Type | Item Type |
| 8 | Item Company | Company or Organization |
| 9 | Warehouse | Warehouse |
| 10 | Bill or Invoice | Bill or Invoice |
| 11 | Employee | Person or Human |
| 12 | Customer Account | Account |
| 13 | Vendor/Supplier Account | Account |
| 14 | Personal/General Account | Account |
| 15 | Purchase Bill or Invoice | Bill or Invoice |
| 16 | Sale Bill or Invoice | Bill or Invoice |

**Comment by mbrig-co** [comment]
**Normalization & performance solution:**
Store most of the too much normalized tables mostly used ones fully de-normalized in case of update used the fully normalized ones but in case of access or select use the fully de-normalized ones.

**Comment by mbrig-co** [comment]
## RAW data for some entities of the app

<table>
  <caption>Users</caption>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Date of Birth (DOB)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Ahmad</td>
      <td>Afghan</td>
      <td>1992 Jan 1</td>
    </tr>
  </tbody>
</table>
